FROM jenkins/jenkins:lts

USER root

RUN apt-get update -o Acquire::Check-Valid-Until=false && \
    apt-get install -y --no-install-recommends \
    docker.io \
    make \
    g++ \
    curl && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
